# Application User
### Login Application User
POST http://localhost:8080/{{webapp_context}}/login
Content-Type: application/x-www-form-urlencoded

username = ui-user &
password = ui-user

### Logout Application User
# @no-redirect
POST http://localhost:8080/{{webapp_context}}/logout

### UI   (Application user can open application UI )
# @no-redirect
GET http://localhost:8080/{{webapp_context}}/

### Internal Web service  (Application user can execute the Dirivation endpoint from the internal web services)
# @no-redirect
GET http://localhost:8080/{{webapp_context}}/web-service/internal/dirivation

# Extrenal service user

### External Web service UI   (Extrenal user can get a list of the external web services via UI)
# @no-redirect
GET http://localhost:8080/{{webapp_context}}/web-service/external
Authorization: Basic ws-ext-user ws-ext-user

### External Web service   (Extrenal user can execute the Entity endpoint from the external web services)
# @no-redirect
GET http://localhost:8080/{{webapp_context}}/web-service/external/entity
Authorization: Basic ws-ext-user ws-ext-user

### External Web service   (Extrenal user can execute the Schedule endpoint from the external web services )
# @no-redirect
GET http://localhost:8080/{{webapp_context}}/web-service/external/schedule
Authorization: Basic ws-ext-user ws-ext-user